// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common.proto

package com.nekonade.common.proto;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RaidBattleEffectDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RaidBattleEffectDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string effectId = 1;</code>
     */
    java.lang.String getEffectId();
    /**
     * <code>string effectId = 1;</code>
     */
    com.google.protobuf.ByteString
        getEffectIdBytes();

    /**
     * <code>int32 effectProp = 2;</code>
     */
    int getEffectProp();

    /**
     * <code>int32 effectType = 3;</code>
     */
    int getEffectType();

    /**
     * <code>int32 effectStack = 5;</code>
     */
    int getEffectStack();

    /**
     * <code>int32 effectMaxStack = 6;</code>
     */
    int getEffectMaxStack();

    /**
     * <code>sint32 effectiveSecond = 7;</code>
     */
    int getEffectiveSecond();

    /**
     * <code>sint32 effectiveTurn = 8;</code>
     */
    int getEffectiveTurn();

    /**
     * <code>int32 dispelByOther = 9;</code>
     */
    int getDispelByOther();

    /**
     * <code>double value1 = 10;</code>
     */
    double getValue1();

    /**
     * <code>double value2 = 11;</code>
     */
    double getValue2();

    /**
     * <code>double value3 = 12;</code>
     */
    double getValue3();

    /**
     * <code>double value4 = 13;</code>
     */
    double getValue4();

    /**
     * <code>string description = 21;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 21;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code RaidBattleEffectDTO}
   */
  public  static final class RaidBattleEffectDTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RaidBattleEffectDTO)
      RaidBattleEffectDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RaidBattleEffectDTO.newBuilder() to construct.
    private RaidBattleEffectDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RaidBattleEffectDTO() {
      effectId_ = "";
      effectProp_ = 0;
      effectType_ = 0;
      effectStack_ = 0;
      effectMaxStack_ = 0;
      effectiveSecond_ = 0;
      effectiveTurn_ = 0;
      dispelByOther_ = 0;
      value1_ = 0D;
      value2_ = 0D;
      value3_ = 0D;
      value4_ = 0D;
      description_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RaidBattleEffectDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              effectId_ = s;
              break;
            }
            case 16: {

              effectProp_ = input.readInt32();
              break;
            }
            case 24: {

              effectType_ = input.readInt32();
              break;
            }
            case 40: {

              effectStack_ = input.readInt32();
              break;
            }
            case 48: {

              effectMaxStack_ = input.readInt32();
              break;
            }
            case 56: {

              effectiveSecond_ = input.readSInt32();
              break;
            }
            case 64: {

              effectiveTurn_ = input.readSInt32();
              break;
            }
            case 72: {

              dispelByOther_ = input.readInt32();
              break;
            }
            case 81: {

              value1_ = input.readDouble();
              break;
            }
            case 89: {

              value2_ = input.readDouble();
              break;
            }
            case 97: {

              value3_ = input.readDouble();
              break;
            }
            case 105: {

              value4_ = input.readDouble();
              break;
            }
            case 170: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nekonade.common.proto.Common.internal_static_RaidBattleEffectDTO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nekonade.common.proto.Common.internal_static_RaidBattleEffectDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nekonade.common.proto.Common.RaidBattleEffectDTO.class, com.nekonade.common.proto.Common.RaidBattleEffectDTO.Builder.class);
    }

    public static final int EFFECTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object effectId_;
    /**
     * <code>string effectId = 1;</code>
     */
    public java.lang.String getEffectId() {
      java.lang.Object ref = effectId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        effectId_ = s;
        return s;
      }
    }
    /**
     * <code>string effectId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEffectIdBytes() {
      java.lang.Object ref = effectId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        effectId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EFFECTPROP_FIELD_NUMBER = 2;
    private int effectProp_;
    /**
     * <code>int32 effectProp = 2;</code>
     */
    public int getEffectProp() {
      return effectProp_;
    }

    public static final int EFFECTTYPE_FIELD_NUMBER = 3;
    private int effectType_;
    /**
     * <code>int32 effectType = 3;</code>
     */
    public int getEffectType() {
      return effectType_;
    }

    public static final int EFFECTSTACK_FIELD_NUMBER = 5;
    private int effectStack_;
    /**
     * <code>int32 effectStack = 5;</code>
     */
    public int getEffectStack() {
      return effectStack_;
    }

    public static final int EFFECTMAXSTACK_FIELD_NUMBER = 6;
    private int effectMaxStack_;
    /**
     * <code>int32 effectMaxStack = 6;</code>
     */
    public int getEffectMaxStack() {
      return effectMaxStack_;
    }

    public static final int EFFECTIVESECOND_FIELD_NUMBER = 7;
    private int effectiveSecond_;
    /**
     * <code>sint32 effectiveSecond = 7;</code>
     */
    public int getEffectiveSecond() {
      return effectiveSecond_;
    }

    public static final int EFFECTIVETURN_FIELD_NUMBER = 8;
    private int effectiveTurn_;
    /**
     * <code>sint32 effectiveTurn = 8;</code>
     */
    public int getEffectiveTurn() {
      return effectiveTurn_;
    }

    public static final int DISPELBYOTHER_FIELD_NUMBER = 9;
    private int dispelByOther_;
    /**
     * <code>int32 dispelByOther = 9;</code>
     */
    public int getDispelByOther() {
      return dispelByOther_;
    }

    public static final int VALUE1_FIELD_NUMBER = 10;
    private double value1_;
    /**
     * <code>double value1 = 10;</code>
     */
    public double getValue1() {
      return value1_;
    }

    public static final int VALUE2_FIELD_NUMBER = 11;
    private double value2_;
    /**
     * <code>double value2 = 11;</code>
     */
    public double getValue2() {
      return value2_;
    }

    public static final int VALUE3_FIELD_NUMBER = 12;
    private double value3_;
    /**
     * <code>double value3 = 12;</code>
     */
    public double getValue3() {
      return value3_;
    }

    public static final int VALUE4_FIELD_NUMBER = 13;
    private double value4_;
    /**
     * <code>double value4 = 13;</code>
     */
    public double getValue4() {
      return value4_;
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 21;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 21;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 21;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getEffectIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, effectId_);
      }
      if (effectProp_ != 0) {
        output.writeInt32(2, effectProp_);
      }
      if (effectType_ != 0) {
        output.writeInt32(3, effectType_);
      }
      if (effectStack_ != 0) {
        output.writeInt32(5, effectStack_);
      }
      if (effectMaxStack_ != 0) {
        output.writeInt32(6, effectMaxStack_);
      }
      if (effectiveSecond_ != 0) {
        output.writeSInt32(7, effectiveSecond_);
      }
      if (effectiveTurn_ != 0) {
        output.writeSInt32(8, effectiveTurn_);
      }
      if (dispelByOther_ != 0) {
        output.writeInt32(9, dispelByOther_);
      }
      if (value1_ != 0D) {
        output.writeDouble(10, value1_);
      }
      if (value2_ != 0D) {
        output.writeDouble(11, value2_);
      }
      if (value3_ != 0D) {
        output.writeDouble(12, value3_);
      }
      if (value4_ != 0D) {
        output.writeDouble(13, value4_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 21, description_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getEffectIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, effectId_);
      }
      if (effectProp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, effectProp_);
      }
      if (effectType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, effectType_);
      }
      if (effectStack_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, effectStack_);
      }
      if (effectMaxStack_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, effectMaxStack_);
      }
      if (effectiveSecond_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(7, effectiveSecond_);
      }
      if (effectiveTurn_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(8, effectiveTurn_);
      }
      if (dispelByOther_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, dispelByOther_);
      }
      if (value1_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(10, value1_);
      }
      if (value2_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(11, value2_);
      }
      if (value3_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(12, value3_);
      }
      if (value4_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(13, value4_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(21, description_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nekonade.common.proto.Common.RaidBattleEffectDTO)) {
        return super.equals(obj);
      }
      com.nekonade.common.proto.Common.RaidBattleEffectDTO other = (com.nekonade.common.proto.Common.RaidBattleEffectDTO) obj;

      boolean result = true;
      result = result && getEffectId()
          .equals(other.getEffectId());
      result = result && (getEffectProp()
          == other.getEffectProp());
      result = result && (getEffectType()
          == other.getEffectType());
      result = result && (getEffectStack()
          == other.getEffectStack());
      result = result && (getEffectMaxStack()
          == other.getEffectMaxStack());
      result = result && (getEffectiveSecond()
          == other.getEffectiveSecond());
      result = result && (getEffectiveTurn()
          == other.getEffectiveTurn());
      result = result && (getDispelByOther()
          == other.getDispelByOther());
      result = result && (
          java.lang.Double.doubleToLongBits(getValue1())
          == java.lang.Double.doubleToLongBits(
              other.getValue1()));
      result = result && (
          java.lang.Double.doubleToLongBits(getValue2())
          == java.lang.Double.doubleToLongBits(
              other.getValue2()));
      result = result && (
          java.lang.Double.doubleToLongBits(getValue3())
          == java.lang.Double.doubleToLongBits(
              other.getValue3()));
      result = result && (
          java.lang.Double.doubleToLongBits(getValue4())
          == java.lang.Double.doubleToLongBits(
              other.getValue4()));
      result = result && getDescription()
          .equals(other.getDescription());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EFFECTID_FIELD_NUMBER;
      hash = (53 * hash) + getEffectId().hashCode();
      hash = (37 * hash) + EFFECTPROP_FIELD_NUMBER;
      hash = (53 * hash) + getEffectProp();
      hash = (37 * hash) + EFFECTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getEffectType();
      hash = (37 * hash) + EFFECTSTACK_FIELD_NUMBER;
      hash = (53 * hash) + getEffectStack();
      hash = (37 * hash) + EFFECTMAXSTACK_FIELD_NUMBER;
      hash = (53 * hash) + getEffectMaxStack();
      hash = (37 * hash) + EFFECTIVESECOND_FIELD_NUMBER;
      hash = (53 * hash) + getEffectiveSecond();
      hash = (37 * hash) + EFFECTIVETURN_FIELD_NUMBER;
      hash = (53 * hash) + getEffectiveTurn();
      hash = (37 * hash) + DISPELBYOTHER_FIELD_NUMBER;
      hash = (53 * hash) + getDispelByOther();
      hash = (37 * hash) + VALUE1_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getValue1()));
      hash = (37 * hash) + VALUE2_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getValue2()));
      hash = (37 * hash) + VALUE3_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getValue3()));
      hash = (37 * hash) + VALUE4_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getValue4()));
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nekonade.common.proto.Common.RaidBattleEffectDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nekonade.common.proto.Common.RaidBattleEffectDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nekonade.common.proto.Common.RaidBattleEffectDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nekonade.common.proto.Common.RaidBattleEffectDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nekonade.common.proto.Common.RaidBattleEffectDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nekonade.common.proto.Common.RaidBattleEffectDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nekonade.common.proto.Common.RaidBattleEffectDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nekonade.common.proto.Common.RaidBattleEffectDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nekonade.common.proto.Common.RaidBattleEffectDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.nekonade.common.proto.Common.RaidBattleEffectDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nekonade.common.proto.Common.RaidBattleEffectDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nekonade.common.proto.Common.RaidBattleEffectDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nekonade.common.proto.Common.RaidBattleEffectDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RaidBattleEffectDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RaidBattleEffectDTO)
        com.nekonade.common.proto.Common.RaidBattleEffectDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nekonade.common.proto.Common.internal_static_RaidBattleEffectDTO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nekonade.common.proto.Common.internal_static_RaidBattleEffectDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nekonade.common.proto.Common.RaidBattleEffectDTO.class, com.nekonade.common.proto.Common.RaidBattleEffectDTO.Builder.class);
      }

      // Construct using com.nekonade.common.proto.Common.RaidBattleEffectDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        effectId_ = "";

        effectProp_ = 0;

        effectType_ = 0;

        effectStack_ = 0;

        effectMaxStack_ = 0;

        effectiveSecond_ = 0;

        effectiveTurn_ = 0;

        dispelByOther_ = 0;

        value1_ = 0D;

        value2_ = 0D;

        value3_ = 0D;

        value4_ = 0D;

        description_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nekonade.common.proto.Common.internal_static_RaidBattleEffectDTO_descriptor;
      }

      public com.nekonade.common.proto.Common.RaidBattleEffectDTO getDefaultInstanceForType() {
        return com.nekonade.common.proto.Common.RaidBattleEffectDTO.getDefaultInstance();
      }

      public com.nekonade.common.proto.Common.RaidBattleEffectDTO build() {
        com.nekonade.common.proto.Common.RaidBattleEffectDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.nekonade.common.proto.Common.RaidBattleEffectDTO buildPartial() {
        com.nekonade.common.proto.Common.RaidBattleEffectDTO result = new com.nekonade.common.proto.Common.RaidBattleEffectDTO(this);
        result.effectId_ = effectId_;
        result.effectProp_ = effectProp_;
        result.effectType_ = effectType_;
        result.effectStack_ = effectStack_;
        result.effectMaxStack_ = effectMaxStack_;
        result.effectiveSecond_ = effectiveSecond_;
        result.effectiveTurn_ = effectiveTurn_;
        result.dispelByOther_ = dispelByOther_;
        result.value1_ = value1_;
        result.value2_ = value2_;
        result.value3_ = value3_;
        result.value4_ = value4_;
        result.description_ = description_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nekonade.common.proto.Common.RaidBattleEffectDTO) {
          return mergeFrom((com.nekonade.common.proto.Common.RaidBattleEffectDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nekonade.common.proto.Common.RaidBattleEffectDTO other) {
        if (other == com.nekonade.common.proto.Common.RaidBattleEffectDTO.getDefaultInstance()) return this;
        if (!other.getEffectId().isEmpty()) {
          effectId_ = other.effectId_;
          onChanged();
        }
        if (other.getEffectProp() != 0) {
          setEffectProp(other.getEffectProp());
        }
        if (other.getEffectType() != 0) {
          setEffectType(other.getEffectType());
        }
        if (other.getEffectStack() != 0) {
          setEffectStack(other.getEffectStack());
        }
        if (other.getEffectMaxStack() != 0) {
          setEffectMaxStack(other.getEffectMaxStack());
        }
        if (other.getEffectiveSecond() != 0) {
          setEffectiveSecond(other.getEffectiveSecond());
        }
        if (other.getEffectiveTurn() != 0) {
          setEffectiveTurn(other.getEffectiveTurn());
        }
        if (other.getDispelByOther() != 0) {
          setDispelByOther(other.getDispelByOther());
        }
        if (other.getValue1() != 0D) {
          setValue1(other.getValue1());
        }
        if (other.getValue2() != 0D) {
          setValue2(other.getValue2());
        }
        if (other.getValue3() != 0D) {
          setValue3(other.getValue3());
        }
        if (other.getValue4() != 0D) {
          setValue4(other.getValue4());
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nekonade.common.proto.Common.RaidBattleEffectDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nekonade.common.proto.Common.RaidBattleEffectDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object effectId_ = "";
      /**
       * <code>string effectId = 1;</code>
       */
      public java.lang.String getEffectId() {
        java.lang.Object ref = effectId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          effectId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string effectId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEffectIdBytes() {
        java.lang.Object ref = effectId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          effectId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string effectId = 1;</code>
       */
      public Builder setEffectId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        effectId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string effectId = 1;</code>
       */
      public Builder clearEffectId() {
        
        effectId_ = getDefaultInstance().getEffectId();
        onChanged();
        return this;
      }
      /**
       * <code>string effectId = 1;</code>
       */
      public Builder setEffectIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        effectId_ = value;
        onChanged();
        return this;
      }

      private int effectProp_ ;
      /**
       * <code>int32 effectProp = 2;</code>
       */
      public int getEffectProp() {
        return effectProp_;
      }
      /**
       * <code>int32 effectProp = 2;</code>
       */
      public Builder setEffectProp(int value) {
        
        effectProp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 effectProp = 2;</code>
       */
      public Builder clearEffectProp() {
        
        effectProp_ = 0;
        onChanged();
        return this;
      }

      private int effectType_ ;
      /**
       * <code>int32 effectType = 3;</code>
       */
      public int getEffectType() {
        return effectType_;
      }
      /**
       * <code>int32 effectType = 3;</code>
       */
      public Builder setEffectType(int value) {
        
        effectType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 effectType = 3;</code>
       */
      public Builder clearEffectType() {
        
        effectType_ = 0;
        onChanged();
        return this;
      }

      private int effectStack_ ;
      /**
       * <code>int32 effectStack = 5;</code>
       */
      public int getEffectStack() {
        return effectStack_;
      }
      /**
       * <code>int32 effectStack = 5;</code>
       */
      public Builder setEffectStack(int value) {
        
        effectStack_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 effectStack = 5;</code>
       */
      public Builder clearEffectStack() {
        
        effectStack_ = 0;
        onChanged();
        return this;
      }

      private int effectMaxStack_ ;
      /**
       * <code>int32 effectMaxStack = 6;</code>
       */
      public int getEffectMaxStack() {
        return effectMaxStack_;
      }
      /**
       * <code>int32 effectMaxStack = 6;</code>
       */
      public Builder setEffectMaxStack(int value) {
        
        effectMaxStack_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 effectMaxStack = 6;</code>
       */
      public Builder clearEffectMaxStack() {
        
        effectMaxStack_ = 0;
        onChanged();
        return this;
      }

      private int effectiveSecond_ ;
      /**
       * <code>sint32 effectiveSecond = 7;</code>
       */
      public int getEffectiveSecond() {
        return effectiveSecond_;
      }
      /**
       * <code>sint32 effectiveSecond = 7;</code>
       */
      public Builder setEffectiveSecond(int value) {
        
        effectiveSecond_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 effectiveSecond = 7;</code>
       */
      public Builder clearEffectiveSecond() {
        
        effectiveSecond_ = 0;
        onChanged();
        return this;
      }

      private int effectiveTurn_ ;
      /**
       * <code>sint32 effectiveTurn = 8;</code>
       */
      public int getEffectiveTurn() {
        return effectiveTurn_;
      }
      /**
       * <code>sint32 effectiveTurn = 8;</code>
       */
      public Builder setEffectiveTurn(int value) {
        
        effectiveTurn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 effectiveTurn = 8;</code>
       */
      public Builder clearEffectiveTurn() {
        
        effectiveTurn_ = 0;
        onChanged();
        return this;
      }

      private int dispelByOther_ ;
      /**
       * <code>int32 dispelByOther = 9;</code>
       */
      public int getDispelByOther() {
        return dispelByOther_;
      }
      /**
       * <code>int32 dispelByOther = 9;</code>
       */
      public Builder setDispelByOther(int value) {
        
        dispelByOther_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dispelByOther = 9;</code>
       */
      public Builder clearDispelByOther() {
        
        dispelByOther_ = 0;
        onChanged();
        return this;
      }

      private double value1_ ;
      /**
       * <code>double value1 = 10;</code>
       */
      public double getValue1() {
        return value1_;
      }
      /**
       * <code>double value1 = 10;</code>
       */
      public Builder setValue1(double value) {
        
        value1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double value1 = 10;</code>
       */
      public Builder clearValue1() {
        
        value1_ = 0D;
        onChanged();
        return this;
      }

      private double value2_ ;
      /**
       * <code>double value2 = 11;</code>
       */
      public double getValue2() {
        return value2_;
      }
      /**
       * <code>double value2 = 11;</code>
       */
      public Builder setValue2(double value) {
        
        value2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double value2 = 11;</code>
       */
      public Builder clearValue2() {
        
        value2_ = 0D;
        onChanged();
        return this;
      }

      private double value3_ ;
      /**
       * <code>double value3 = 12;</code>
       */
      public double getValue3() {
        return value3_;
      }
      /**
       * <code>double value3 = 12;</code>
       */
      public Builder setValue3(double value) {
        
        value3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double value3 = 12;</code>
       */
      public Builder clearValue3() {
        
        value3_ = 0D;
        onChanged();
        return this;
      }

      private double value4_ ;
      /**
       * <code>double value4 = 13;</code>
       */
      public double getValue4() {
        return value4_;
      }
      /**
       * <code>double value4 = 13;</code>
       */
      public Builder setValue4(double value) {
        
        value4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double value4 = 13;</code>
       */
      public Builder clearValue4() {
        
        value4_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 21;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 21;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 21;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 21;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 21;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RaidBattleEffectDTO)
    }

    // @@protoc_insertion_point(class_scope:RaidBattleEffectDTO)
    private static final com.nekonade.common.proto.Common.RaidBattleEffectDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nekonade.common.proto.Common.RaidBattleEffectDTO();
    }

    public static com.nekonade.common.proto.Common.RaidBattleEffectDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RaidBattleEffectDTO>
        PARSER = new com.google.protobuf.AbstractParser<RaidBattleEffectDTO>() {
      public RaidBattleEffectDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RaidBattleEffectDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RaidBattleEffectDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RaidBattleEffectDTO> getParserForType() {
      return PARSER;
    }

    public com.nekonade.common.proto.Common.RaidBattleEffectDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RaidBattleEffectDTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RaidBattleEffectDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Common.proto\"\244\002\n\023RaidBattleEffectDTO\022\020" +
      "\n\010effectId\030\001 \001(\t\022\022\n\neffectProp\030\002 \001(\005\022\022\n\n" +
      "effectType\030\003 \001(\005\022\023\n\013effectStack\030\005 \001(\005\022\026\n" +
      "\016effectMaxStack\030\006 \001(\005\022\027\n\017effectiveSecond" +
      "\030\007 \001(\021\022\025\n\reffectiveTurn\030\010 \001(\021\022\025\n\rdispelB" +
      "yOther\030\t \001(\005\022\016\n\006value1\030\n \001(\001\022\016\n\006value2\030\013" +
      " \001(\001\022\016\n\006value3\030\014 \001(\001\022\016\n\006value4\030\r \001(\001\022\023\n\013" +
      "description\030\025 \001(\tJ\004\010\004\020\005J\004\010\016\020\025B\033\n\031com.nek" +
      "onade.common.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RaidBattleEffectDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RaidBattleEffectDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RaidBattleEffectDTO_descriptor,
        new java.lang.String[] { "EffectId", "EffectProp", "EffectType", "EffectStack", "EffectMaxStack", "EffectiveSecond", "EffectiveTurn", "DispelByOther", "Value1", "Value2", "Value3", "Value4", "Description", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
