game:
  server:
    config:
      service-id: 101   #服务器中配置服务Id
      server-id: 10101  #当前服务器的id
      business-game-message-topic: business-game-message-topic-${game.server.config.server-id}
      gateway-game-message-topic: gateway-game-message-topic
    log:
      log-game-message-topic: log-gamelogic-message-topic
      who-am-i: NekoServer
  channel:
    gateway-game-message-topic: gateway-game-message-topic
    business-game-message-topic: business-game-message-topic
    rpc-request-game-message-topic: rpc-request-game-message-topic
    rpc-response-game-message-topic: rpc-response-game-message-topic
    topic-group-id: ${game.server.config.server-id}