// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ThirdMsgBody.proto

package com.nekonade.network.param.game.message.body;

public final class ThirdMsgBody {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ThirdMsgRequestBody_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_ThirdMsgRequestBody_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ThirdMsgResponseBody_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_ThirdMsgResponseBody_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\022ThirdMsgBody.proto\"5\n\023ThirdMsgRequestB" +
                        "ody\022\016\n\006value1\030\001 \001(\t\022\016\n\006value2\030\002 \001(\003\"F\n\024T" +
                        "hirdMsgResponseBody\022\016\n\006value1\030\001 \001(\t\022\016\n\006v" +
                        "alue2\030\002 \001(\005\022\016\n\006value3\030\003 \001(\tB,\n\034com.mygam" +
                        "e.game.message.bodyB\014ThirdMsgBody"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_ThirdMsgRequestBody_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_ThirdMsgRequestBody_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_ThirdMsgRequestBody_descriptor,
                new String[]{"Value1", "Value2",});
        internal_static_ThirdMsgResponseBody_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_ThirdMsgResponseBody_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_ThirdMsgResponseBody_descriptor,
                new String[]{"Value1", "Value2", "Value3",});
    }

    private ThirdMsgBody() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    public interface ThirdMsgRequestBodyOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ThirdMsgRequestBody)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string value1 = 1;</code>
         */
        boolean hasValue1();

        /**
         * <code>optional string value1 = 1;</code>
         */
        String getValue1();

        /**
         * <code>optional string value1 = 1;</code>
         */
        com.google.protobuf.ByteString
        getValue1Bytes();

        /**
         * <pre>
         * 表示一个long类型的值
         * </pre>
         *
         * <code>optional int64 value2 = 2;</code>
         */
        boolean hasValue2();

        /**
         * <pre>
         * 表示一个long类型的值
         * </pre>
         *
         * <code>optional int64 value2 = 2;</code>
         */
        long getValue2();
    }

    public interface ThirdMsgResponseBodyOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ThirdMsgResponseBody)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string value1 = 1;</code>
         */
        boolean hasValue1();

        /**
         * <code>optional string value1 = 1;</code>
         */
        String getValue1();

        /**
         * <code>optional string value1 = 1;</code>
         */
        com.google.protobuf.ByteString
        getValue1Bytes();

        /**
         * <pre>
         * 表示一个int类型的值
         * </pre>
         *
         * <code>optional int32 value2 = 2;</code>
         */
        boolean hasValue2();

        /**
         * <pre>
         * 表示一个int类型的值
         * </pre>
         *
         * <code>optional int32 value2 = 2;</code>
         */
        int getValue2();

        /**
         * <code>optional string value3 = 3;</code>
         */
        boolean hasValue3();

        /**
         * <code>optional string value3 = 3;</code>
         */
        String getValue3();

        /**
         * <code>optional string value3 = 3;</code>
         */
        com.google.protobuf.ByteString
        getValue3Bytes();
    }

    /**
     * <pre>
     * 请求消息消息体
     * </pre>
     * <p>
     * Protobuf type {@code ThirdMsgRequestBody}
     */
    public static final class ThirdMsgRequestBody extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:ThirdMsgRequestBody)
            ThirdMsgRequestBodyOrBuilder {
        public static final int VALUE1_FIELD_NUMBER = 1;
        public static final int VALUE2_FIELD_NUMBER = 2;
        @Deprecated
        public static final com.google.protobuf.Parser<ThirdMsgRequestBody>
                PARSER = new com.google.protobuf.AbstractParser<ThirdMsgRequestBody>() {
            @Override
            public ThirdMsgRequestBody parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new ThirdMsgRequestBody(input, extensionRegistry);
            }
        };
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:ThirdMsgRequestBody)
        private static final ThirdMsgRequestBody DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new ThirdMsgRequestBody();
        }

        private int bitField0_;
        private volatile Object value1_;
        private long value2_;
        private byte memoizedIsInitialized = -1;

        // Use ThirdMsgRequestBody.newBuilder() to construct.
        private ThirdMsgRequestBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ThirdMsgRequestBody() {
            value1_ = "";
            value2_ = 0L;
        }

        private ThirdMsgRequestBody(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            value1_ = bs;
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            value2_ = input.readInt64();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return internal_static_ThirdMsgRequestBody_descriptor;
        }

        public static ThirdMsgRequestBody parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ThirdMsgRequestBody parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ThirdMsgRequestBody parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ThirdMsgRequestBody parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ThirdMsgRequestBody parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ThirdMsgRequestBody parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ThirdMsgRequestBody parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ThirdMsgRequestBody parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static ThirdMsgRequestBody parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static ThirdMsgRequestBody parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static ThirdMsgRequestBody parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ThirdMsgRequestBody parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(ThirdMsgRequestBody prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static ThirdMsgRequestBody getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<ThirdMsgRequestBody> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return internal_static_ThirdMsgRequestBody_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ThirdMsgRequestBody.class, ThirdMsgRequestBody.Builder.class);
        }

        /**
         * <code>optional string value1 = 1;</code>
         */
        public boolean hasValue1() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional string value1 = 1;</code>
         */
        public String getValue1() {
            Object ref = value1_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    value1_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string value1 = 1;</code>
         */
        public com.google.protobuf.ByteString
        getValue1Bytes() {
            Object ref = value1_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                value1_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 表示一个long类型的值
         * </pre>
         *
         * <code>optional int64 value2 = 2;</code>
         */
        public boolean hasValue2() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <pre>
         * 表示一个long类型的值
         * </pre>
         *
         * <code>optional int64 value2 = 2;</code>
         */
        public long getValue2() {
            return value2_;
        }

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, value1_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt64(2, value2_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, value1_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(2, value2_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof ThirdMsgRequestBody)) {
                return super.equals(obj);
            }
            ThirdMsgRequestBody other = (ThirdMsgRequestBody) obj;

            boolean result = true;
            result = result && (hasValue1() == other.hasValue1());
            if (hasValue1()) {
                result = result && getValue1()
                        .equals(other.getValue1());
            }
            result = result && (hasValue2() == other.hasValue2());
            if (hasValue2()) {
                result = result && (getValue2()
                        == other.getValue2());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasValue1()) {
                hash = (37 * hash) + VALUE1_FIELD_NUMBER;
                hash = (53 * hash) + getValue1().hashCode();
            }
            if (hasValue2()) {
                hash = (37 * hash) + VALUE2_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                        getValue2());
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<ThirdMsgRequestBody> getParserForType() {
            return PARSER;
        }

        @Override
        public ThirdMsgRequestBody getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * <pre>
         * 请求消息消息体
         * </pre>
         * <p>
         * Protobuf type {@code ThirdMsgRequestBody}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:ThirdMsgRequestBody)
                ThirdMsgRequestBodyOrBuilder {
            private int bitField0_;
            private Object value1_ = "";
            private long value2_;

            // Construct using ThirdMsgRequestBody.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return internal_static_ThirdMsgRequestBody_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return internal_static_ThirdMsgRequestBody_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ThirdMsgRequestBody.class, ThirdMsgRequestBody.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                value1_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                value2_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return internal_static_ThirdMsgRequestBody_descriptor;
            }

            @Override
            public ThirdMsgRequestBody getDefaultInstanceForType() {
                return ThirdMsgRequestBody.getDefaultInstance();
            }

            @Override
            public ThirdMsgRequestBody build() {
                ThirdMsgRequestBody result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public ThirdMsgRequestBody buildPartial() {
                ThirdMsgRequestBody result = new ThirdMsgRequestBody(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.value1_ = value1_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.value2_ = value2_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ThirdMsgRequestBody) {
                    return mergeFrom((ThirdMsgRequestBody) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ThirdMsgRequestBody other) {
                if (other == ThirdMsgRequestBody.getDefaultInstance()) return this;
                if (other.hasValue1()) {
                    bitField0_ |= 0x00000001;
                    value1_ = other.value1_;
                    onChanged();
                }
                if (other.hasValue2()) {
                    setValue2(other.getValue2());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                ThirdMsgRequestBody parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ThirdMsgRequestBody) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>optional string value1 = 1;</code>
             */
            public boolean hasValue1() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional string value1 = 1;</code>
             */
            public String getValue1() {
                Object ref = value1_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        value1_ = s;
                    }
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string value1 = 1;</code>
             */
            public Builder setValue1(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                value1_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string value1 = 1;</code>
             */
            public com.google.protobuf.ByteString
            getValue1Bytes() {
                Object ref = value1_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    value1_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string value1 = 1;</code>
             */
            public Builder setValue1Bytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                value1_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string value1 = 1;</code>
             */
            public Builder clearValue1() {
                bitField0_ = (bitField0_ & ~0x00000001);
                value1_ = getDefaultInstance().getValue1();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 表示一个long类型的值
             * </pre>
             *
             * <code>optional int64 value2 = 2;</code>
             */
            public boolean hasValue2() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <pre>
             * 表示一个long类型的值
             * </pre>
             *
             * <code>optional int64 value2 = 2;</code>
             */
            public long getValue2() {
                return value2_;
            }

            /**
             * <pre>
             * 表示一个long类型的值
             * </pre>
             *
             * <code>optional int64 value2 = 2;</code>
             */
            public Builder setValue2(long value) {
                bitField0_ |= 0x00000002;
                value2_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 表示一个long类型的值
             * </pre>
             *
             * <code>optional int64 value2 = 2;</code>
             */
            public Builder clearValue2() {
                bitField0_ = (bitField0_ & ~0x00000002);
                value2_ = 0L;
                onChanged();
                return this;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:ThirdMsgRequestBody)
        }

    }

    /**
     * <pre>
     * 响应消息消息体
     * </pre>
     * <p>
     * Protobuf type {@code ThirdMsgResponseBody}
     */
    public static final class ThirdMsgResponseBody extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:ThirdMsgResponseBody)
            ThirdMsgResponseBodyOrBuilder {
        public static final int VALUE1_FIELD_NUMBER = 1;
        public static final int VALUE2_FIELD_NUMBER = 2;
        public static final int VALUE3_FIELD_NUMBER = 3;
        @Deprecated
        public static final com.google.protobuf.Parser<ThirdMsgResponseBody>
                PARSER = new com.google.protobuf.AbstractParser<ThirdMsgResponseBody>() {
            @Override
            public ThirdMsgResponseBody parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new ThirdMsgResponseBody(input, extensionRegistry);
            }
        };
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:ThirdMsgResponseBody)
        private static final ThirdMsgResponseBody DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new ThirdMsgResponseBody();
        }

        private int bitField0_;
        private volatile Object value1_;
        private int value2_;
        private volatile Object value3_;
        private byte memoizedIsInitialized = -1;

        // Use ThirdMsgResponseBody.newBuilder() to construct.
        private ThirdMsgResponseBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ThirdMsgResponseBody() {
            value1_ = "";
            value2_ = 0;
            value3_ = "";
        }
        private ThirdMsgResponseBody(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            value1_ = bs;
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            value2_ = input.readInt32();
                            break;
                        }
                        case 26: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000004;
                            value3_ = bs;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return internal_static_ThirdMsgResponseBody_descriptor;
        }

        public static ThirdMsgResponseBody parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ThirdMsgResponseBody parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ThirdMsgResponseBody parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ThirdMsgResponseBody parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ThirdMsgResponseBody parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ThirdMsgResponseBody parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ThirdMsgResponseBody parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ThirdMsgResponseBody parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static ThirdMsgResponseBody parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static ThirdMsgResponseBody parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static ThirdMsgResponseBody parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ThirdMsgResponseBody parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(ThirdMsgResponseBody prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static ThirdMsgResponseBody getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<ThirdMsgResponseBody> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return internal_static_ThirdMsgResponseBody_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ThirdMsgResponseBody.class, ThirdMsgResponseBody.Builder.class);
        }

        /**
         * <code>optional string value1 = 1;</code>
         */
        public boolean hasValue1() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional string value1 = 1;</code>
         */
        public String getValue1() {
            Object ref = value1_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    value1_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string value1 = 1;</code>
         */
        public com.google.protobuf.ByteString
        getValue1Bytes() {
            Object ref = value1_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                value1_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 表示一个int类型的值
         * </pre>
         *
         * <code>optional int32 value2 = 2;</code>
         */
        public boolean hasValue2() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <pre>
         * 表示一个int类型的值
         * </pre>
         *
         * <code>optional int32 value2 = 2;</code>
         */
        public int getValue2() {
            return value2_;
        }

        /**
         * <code>optional string value3 = 3;</code>
         */
        public boolean hasValue3() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>optional string value3 = 3;</code>
         */
        public String getValue3() {
            Object ref = value3_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    value3_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string value3 = 3;</code>
         */
        public com.google.protobuf.ByteString
        getValue3Bytes() {
            Object ref = value3_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                value3_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, value1_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt32(2, value2_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, value3_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, value1_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, value2_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, value3_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof ThirdMsgResponseBody)) {
                return super.equals(obj);
            }
            ThirdMsgResponseBody other = (ThirdMsgResponseBody) obj;

            boolean result = true;
            result = result && (hasValue1() == other.hasValue1());
            if (hasValue1()) {
                result = result && getValue1()
                        .equals(other.getValue1());
            }
            result = result && (hasValue2() == other.hasValue2());
            if (hasValue2()) {
                result = result && (getValue2()
                        == other.getValue2());
            }
            result = result && (hasValue3() == other.hasValue3());
            if (hasValue3()) {
                result = result && getValue3()
                        .equals(other.getValue3());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasValue1()) {
                hash = (37 * hash) + VALUE1_FIELD_NUMBER;
                hash = (53 * hash) + getValue1().hashCode();
            }
            if (hasValue2()) {
                hash = (37 * hash) + VALUE2_FIELD_NUMBER;
                hash = (53 * hash) + getValue2();
            }
            if (hasValue3()) {
                hash = (37 * hash) + VALUE3_FIELD_NUMBER;
                hash = (53 * hash) + getValue3().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<ThirdMsgResponseBody> getParserForType() {
            return PARSER;
        }

        @Override
        public ThirdMsgResponseBody getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * <pre>
         * 响应消息消息体
         * </pre>
         * <p>
         * Protobuf type {@code ThirdMsgResponseBody}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:ThirdMsgResponseBody)
                ThirdMsgResponseBodyOrBuilder {
            private int bitField0_;
            private Object value1_ = "";
            private int value2_;
            private Object value3_ = "";

            // Construct using ThirdMsgResponseBody.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return internal_static_ThirdMsgResponseBody_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return internal_static_ThirdMsgResponseBody_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ThirdMsgResponseBody.class, ThirdMsgResponseBody.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                value1_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                value2_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                value3_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return internal_static_ThirdMsgResponseBody_descriptor;
            }

            @Override
            public ThirdMsgResponseBody getDefaultInstanceForType() {
                return ThirdMsgResponseBody.getDefaultInstance();
            }

            @Override
            public ThirdMsgResponseBody build() {
                ThirdMsgResponseBody result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public ThirdMsgResponseBody buildPartial() {
                ThirdMsgResponseBody result = new ThirdMsgResponseBody(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.value1_ = value1_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.value2_ = value2_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.value3_ = value3_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ThirdMsgResponseBody) {
                    return mergeFrom((ThirdMsgResponseBody) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ThirdMsgResponseBody other) {
                if (other == ThirdMsgResponseBody.getDefaultInstance()) return this;
                if (other.hasValue1()) {
                    bitField0_ |= 0x00000001;
                    value1_ = other.value1_;
                    onChanged();
                }
                if (other.hasValue2()) {
                    setValue2(other.getValue2());
                }
                if (other.hasValue3()) {
                    bitField0_ |= 0x00000004;
                    value3_ = other.value3_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                ThirdMsgResponseBody parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ThirdMsgResponseBody) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>optional string value1 = 1;</code>
             */
            public boolean hasValue1() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional string value1 = 1;</code>
             */
            public String getValue1() {
                Object ref = value1_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        value1_ = s;
                    }
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string value1 = 1;</code>
             */
            public Builder setValue1(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                value1_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string value1 = 1;</code>
             */
            public com.google.protobuf.ByteString
            getValue1Bytes() {
                Object ref = value1_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    value1_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string value1 = 1;</code>
             */
            public Builder setValue1Bytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                value1_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string value1 = 1;</code>
             */
            public Builder clearValue1() {
                bitField0_ = (bitField0_ & ~0x00000001);
                value1_ = getDefaultInstance().getValue1();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 表示一个int类型的值
             * </pre>
             *
             * <code>optional int32 value2 = 2;</code>
             */
            public boolean hasValue2() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <pre>
             * 表示一个int类型的值
             * </pre>
             *
             * <code>optional int32 value2 = 2;</code>
             */
            public int getValue2() {
                return value2_;
            }

            /**
             * <pre>
             * 表示一个int类型的值
             * </pre>
             *
             * <code>optional int32 value2 = 2;</code>
             */
            public Builder setValue2(int value) {
                bitField0_ |= 0x00000002;
                value2_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 表示一个int类型的值
             * </pre>
             *
             * <code>optional int32 value2 = 2;</code>
             */
            public Builder clearValue2() {
                bitField0_ = (bitField0_ & ~0x00000002);
                value2_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>optional string value3 = 3;</code>
             */
            public boolean hasValue3() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>optional string value3 = 3;</code>
             */
            public String getValue3() {
                Object ref = value3_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        value3_ = s;
                    }
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string value3 = 3;</code>
             */
            public Builder setValue3(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                value3_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string value3 = 3;</code>
             */
            public com.google.protobuf.ByteString
            getValue3Bytes() {
                Object ref = value3_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    value3_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string value3 = 3;</code>
             */
            public Builder setValue3Bytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                value3_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string value3 = 3;</code>
             */
            public Builder clearValue3() {
                bitField0_ = (bitField0_ & ~0x00000004);
                value3_ = getDefaultInstance().getValue3();
                onChanged();
                return this;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:ThirdMsgResponseBody)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
